#!/bin/env bash

if [ "$@" = "Shutdown" ];
then
	shutdown now;
	return 0
elif [ "$@" = "Restart" ];
then
	reboot
	return 0
fi

echo -en "\0prompt\x1f\n"
echo -en "Shutdown\0"
echo -en "icon\x1f~/.local/share/icons/Tela-circle/scalable/apps/system-shutdown.svg\n"
echo -en "Restart\0"
echo -en "icon\x1f~/.local/share/icons/Tela-circle/scalable/apps/system-reboot.svg\n"

