-- wimbleimble's nvim config :)
require("user.options")
require("user.keybinds")
require("user.plugins")
require("user.mason")
require("user.cmp")
require("user.lsp").setup()
require("user.telescope")
require("user.treesitter")
require("user.dashboard")
vim.g.python3_host_prog=vim.fn.expand("~/data/.data-venv/bin/python3")
