-- wimbleimble's nvim config :)
require("user.options")
require("user.plugins")
require("user.keybinds")
require("user.mason")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")

